resolved the issue #1

diff --git a/cryalot b/cryalot
--- a/cryalot
+++ b/cryalot
@@ -22,16 +22,15 @@ for un in $fxnls; do
             basfile="$CRYVAR_BSDIR/${el}/${eun}.bas"
             if [ ! -f "$basfile" ] && [ ! -L "$basfile" ]; then
                 printf "%$(tput cols)s" | tr ' ' '='; echo ""
-                echo -e "Cannot find the basis set file \e[41;97m ${eun} \e[m for element \e[41;97m ${el} \e[m!"
+                echo -e "ATTENTION: Cannot find the basis set file \e[41;97m ${eun} \e[m for element \e[41;97m ${el} \e[m!"
                 echo -e "Found these basis sets for this element:\n   \e[44;97m$(ls -l "$CRYVAR_BSDIR/${el}" | grep -v -e '^total' -e '^l' | gawk '{print $NF}' | xargs | sed 's@\s\+@\\e[m&\\e[44;97m@g')\e[m"
-                read -p "Which of them should we use for this element? Paste the name here:  " selbas
+                read -p "Which of them should we use for this element? Copy from above and paste the name here:  " selbas
                 [ -z "$selbas" ] && echo "Aborting." && exit 2
                 selbas="${selbas%.bas}.bas"
                 aselbas="$aselbas ${el}:${selbas}"
-                ln -s $CRYVAR_BSDIR/${el}/${selbas} $CRYVAR_BSDIR/${el}/${eun}.bas
+                ln -s "$CRYVAR_BSDIR/${el}/${selbas}" "$CRYVAR_BSDIR/${el}/${eun}.bas"
             fi
             [ -L "$CRYVAR_BSDIR/${el}/${eun}.bas" ] && curselbas="$curselbas ${el}:$(basename $(ls -l "$CRYVAR_BSDIR/${el}/${eun}.bas" | gawk '{print $NF}'))"
-            #[ -L "$CRYVAR_BSDIR/${el}/${eun}.bas" ] && echo "Basis ${el}:${eun} is a link to ${el}:${curselbas}"
         done
         if [ -f "${CRYVAR_FXLDIR}/${un}.fxl" ] || [ -L "${CRYVAR_FXLDIR}/${un}.fxl" ]; then
             unn="$(fxnl2cry.sh ${un})"
@@ -50,6 +49,6 @@ for un in $aselbas; do
     el="$(echo "$un" | cut -d : -f 1)"
     realbas="$(echo "$un" | cut -d : -f 2)"
     fakebas="$(ls -l "$CRYVAR_BSDIR/${el}" | grep '^l' | grep "$realbas" | cut -d '>' -f 1 | sed 's@ -$@@' | gawk '{print $NF}')"
-    rm "$CRYVAR_BSDIR/${el}/${fakebas}"
+    [ -f "$CRYVAR_BSDIR/${el}/${fakebas}" ] && rm "$CRYVAR_BSDIR/${el}/${fakebas}" || echo "DEBUG: CAL: for some reason ${fakebas} file was not present!"
 done
 
